# Use an official Ubuntu as a parent image
FROM ubuntu:latest

# Set environment variables to non-interactive to avoid prompts during package installation
ENV DEBIAN_FRONTEND=noninteractive

# Check if the Zscaler certificate exists and copy it
ARG CERT_PATH=/workspace/zscaler.crt

# Set the default value for the argument to avoid errors if CERT_PATH does not exist
RUN echo "Checking for ZScaler certificate at $CERT_PATH" && \
    if [ -f "$CERT_PATH" ]; then \
        echo "ZScaler certificate found, copying to /usr/local/share/ca-certificates" && \
        cp $CERT_PATH /usr/local/share/ca-certificates/zscaler.crt && \
        chmod 644 /usr/local/share/ca-certificates/zscaler.crt && \
        update-ca-certificates --fresh && \
        echo "ZScaler certificate added successfully"; \
    else \
        echo "ZScaler certificate not found. Skipping CA store update."; \
    fi

# Install basic dependencies and update certificates
RUN echo "Installing basic dependencies and updating certificates" && \
    apt-get update && \
    apt-get install -y \
    locales \
    apt-transport-https \
    ca-certificates \
    curl \
    iputils-ping \
    wget \
    vim \
    gnupg2 \
    software-properties-common \
    build-essential && \
    update-ca-certificates && \
    locale-gen en_US.UTF-8 && \
    locale-gen de_DE.UTF-8 && \
    locale-gen fr_FR.UTF-8 && \
    locale-gen es_ES.UTF-8 && \
    locale-gen it_IT.UTF-8 && \
    update-locale LANG=en_US.UTF-8

# Install development tools and dependencies
RUN echo "Installing development tools and dependencies" && \
    apt-get update && \
    apt-get install -y \
    neovim \
    asciidoctor \
    bash \
    jq \
    git \
    kmod \
    fuse-overlayfs \
    parallel \
    tmux \
    lua5.3 \
    lua5.1 \
    luarocks \
    ripgrep \
    fd-find && \
    ln -s $(which fdfind) /usr/local/bin/fd

# Install language runtimes and related tools
RUN echo "Installing language runtimes and related tools" && \
    apt-get update && \
    apt-get install -y \
    python3 \
    python3-pip \
    python3-venv \
    nodejs \
    npm \
    openjdk-11-jdk \
    golang-go \
    cargo \
    php-cli \
    composer

# Install Docker CLI
RUN echo "Installing Docker CLI" && \
    curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg && \
    echo "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null && \
    apt-get update && \
    apt-get install -y docker-ce-cli && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Install Julia
RUN echo "Installing Julia" && \
    wget --no-check-certificate https://julialang-s3.julialang.org/bin/linux/x64/1.8/julia-1.8.5-linux-x86_64.tar.gz && \
    tar -xvzf julia-1.8.5-linux-x86_64.tar.gz && \
    mv julia-1.8.5 /opt/julia && \
    ln -s /opt/julia/bin/julia /usr/local/bin/julia && \
    rm julia-1.8.5-linux-x86_64.tar.gz

# Install dependencies for dev environment
RUN echo "Installing npm dependencies" && \
    npm install -g tree-sitter-cli || echo "Failed to install tree-sitter-cli" && \
    npm install -g neovim || echo "Failed to install neovim"

# Install Perl modules with --no-check-certificate
RUN echo "Installing Perl modules" && \
    cpan App::cpanminus || echo "Failed to install App::cpanminus" && \
    cpanm --no-check-certificate --notest Neovim::Ext || echo "Failed to install Neovim::Ext"

# Set environment variables
ENV NODE_EXTRA_CA_CERTS=/usr/local/share/ca-certificates/zscaler.crt

# Set environment variables for locale
ENV LANG=en_US.UTF-8
ENV LANGUAGE=en_US:en
ENV LC_ALL=en_US.UTF-8
ENV GIT_PAGER=

# Set the working directory for the project and copy the files
WORKDIR /workspace
COPY . /workspace

# Run ruby setup script
RUN echo "Running Ruby setup script" && \
    chmod +x /workspace/scripts/ruby_setup.sh && \
    /bin/bash /workspace/scripts/ruby_setup.sh

# Create and activate a virtual environment and install dependencies
RUN echo "Setting up Python virtual environment" && \
    python3 -m venv /workspace/venv && \
    /bin/bash -c "source /workspace/venv/bin/activate && pip install --no-cache-dir -r /workspace/requirements.txt && pip install --no-cache-dir -r /workspace/requirements-dev.txt && pip list"

# Remove the Zscaler certificate if it was added
RUN echo "Checking for ZScaler certificate to remove" && \
    if [ -f /usr/local/share/ca-certificates/zscaler.crt ]; then \
        echo "ZScaler certificate found, removing" && \
        rm /usr/local/share/ca-certificates/zscaler.crt && \
        update-ca-certificates --fresh && \
        echo "ZScaler certificate removed successfully"; \
    else \
        echo "ZScaler certificate was not added, nothing to remove."; \
    fi

# Start Docker daemon (if needed)
CMD ["bash", "/workspace/scripts/post_create_script.sh"]
