# Use an official Ubuntu as a parent image
FROM ubuntu:latest

# Set environment variables to non-interactive
ENV DEBIAN_FRONTEND=noninteractive

# Install necessary dependencies
RUN apt-get update && \
    apt-get install -y \
    asciidoctor \
    curl \
    nodejs \
    npm && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Install livereloadx
RUN npm install -g livereloadx

# Copy the asciidoc-preview and helper folders into the container
COPY scripts/asciidoc-preview /usr/local/bin/asciidoc-preview
COPY scripts/helper /usr/local/bin/helper

# Make all .sh files in the asciidoc-preview and helper folders executable
RUN find /usr/local/bin/asciidoc-preview /usr/local/bin/helper -name "*.sh" -exec chmod +x {} \;

# Set the working directory for the project
WORKDIR /workspace

# Use the entrypoint script
ENTRYPOINT ["/usr/local/bin/asciidoc-preview/entrypoint.sh"]
