# Use an official Ubuntu as a parent image
FROM ubuntu:latest

# Set environment variables to non-interactive
ENV DEBIAN_FRONTEND=noninteractive

# Copy the Zscaler certificate to the container
COPY zscaler.crt /usr/local/share/ca-certificates/zscaler.crt

# Install basic dependencies and update certificates
RUN apt-get update && \
    apt-get install -y \
    locales \
    apt-transport-https \
    ca-certificates \
    curl \
    wget \
    vim \
    gnupg2 \
    software-properties-common \
    build-essential && \
    update-ca-certificates && \
    locale-gen en_US.UTF-8 && \
    locale-gen de_DE.UTF-8 && \
    locale-gen fr_FR.UTF-8 && \
    locale-gen es_ES.UTF-8 && \
    locale-gen it_IT.UTF-8 && \
    update-locale LANG=en_US.UTF-8

# Install development tools and dependencies
RUN apt-get update && \
    apt-get install -y \
    neovim \
    asciidoctor \
    bash \
    jq \
    git \
    kmod \
    fuse-overlayfs \
    parallel \
    tmux \
    luarocks \
    lua5.1 \
    lua5.3 \
    ripgrep \
    fd-find && \
    ln -s $(which fdfind) /usr/local/bin/fd

# Install language runtimes and related tools
RUN apt-get update && \
    apt-get install -y \
    python3 \
    python3-pip \
    python3-venv \
    nodejs \
    npm \
    openjdk-11-jdk \
    golang-go \
    cargo \
    php-cli \
    composer

# Install Docker CLI
RUN curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg && \
    echo "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null && \
    apt-get update && \
    apt-get install -y docker-ce-cli && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Download and install Julia
RUN wget https://julialang-s3.julialang.org/bin/linux/x64/1.8/julia-1.8.5-linux-x86_64.tar.gz && \
    tar -xvzf julia-1.8.5-linux-x86_64.tar.gz && \
    mv julia-1.8.5 /opt/julia && \
    ln -s /opt/julia/bin/julia /usr/local/bin/julia && \
    rm julia-1.8.5-linux-x86_64.tar.gz

# Set environment variable for Node.js to use the custom CA
ENV NODE_EXTRA_CA_CERTS=/usr/local/share/ca-certificates/zscaler.crt

# Set environment variables for locale
ENV LANG=en_US.UTF-8
ENV LANGUAGE=en_US:en
ENV LC_ALL=en_US.UTF-8
ENV GIT_PAGER=

# Set the working directory for the project and copy the files
WORKDIR /workspace
COPY . /workspace

# Create and activate a virtual environment and install dependencies
RUN python3 -m venv /workspace/venv && \
    /bin/bash -c "source /workspace/venv/bin/activate && pip install --no-cache-dir -r /workspace/requirements.txt && pip install --no-cache-dir -r /workspace/requirements-dev.txt && pip list"

# Start Docker daemon (if needed)
CMD ["bash", "/workspace/scripts/post_create_script.sh"]
