set-option -sg escape-time 10
set-option -g focus-events on
set-option -sa terminal-features ',tmux-256color:RGB'
# For older tmux versions use:
#set-option -ga terminal-overrides ',tmux-256color:Tc'
