set-option -sg escape-time 10
set-option -g focus-events on
# set the terminal-features to the value of the env-variable TERM
set-option -sa terminal-features ',xterm:RGB'
set-option -ga terminal-overrides ',xterm:Tc'"
set-option -sg escape-time 10
set-option -g focus-events on
